[package]
name = "md5sumsum"
version = "0.1.0"
authors = ["AHRAS Yanis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
rustc-serialize = "0.3"
rayon = "1.3.0"